### ISSUE TITLE
Generate Enap_blank.itp

### ISSUE THREAD

**Issue by shafayetrahat** [ricalessandri/Martini3-small-molecules#20]
When using bartender we need a blank.itp( ex. Enap_blank.itp) file for the input of the "write_bartender_inp.py" file. I am seeing a lot of values set in the blank.itp but doesn't know where they came from. There is no proper instruction on how to generate Enap_blank.itp file efficiently. Also, there is no proper instruction in the bartender repository on this topic. Could anyone please explain to me how to generate the Enap_blank.itp? If we need to do it by hand then can anyone share the tricks to set the values in the blankitp file?

**Comment by ricalessandri** [comment]
This has been addressed on the Bartender repo - see https://github.com/rmera/bartender/issues/2.
